### PR TITLE
Improve convergence of epa algorithm in case it's stuck

### PR DESCRIPTION
**Pull request by Ughuuu**
Improves converges by checking if it's stuck. In such a case return a result, as a better solution will not be found, and most likely they are intersecting but not within the EPS.

Also decrease max iterations from 10000 to 100. It usually converges in 4-5 iterations, no need to ever do as many. Also we never really want a precision that big, we are ok with a lower precision most times.

- Fixes https://github.com/dimforge/parry/issues/205

Possibly fixes:
- https://github.com/dimforge/parry/issues/157

### CODE REVIEW

**Comment by Ughuuu** [comment]
With this fix it actually returns a contact (didn't know how to draw the intersection better):

image

Also it does so in 5 iterations, instead of doing 10000 iterations and returning None.

**Comment by Vrixyz** [comment]
Thanks! I'd like to add a test for this scenario, would a setup like https://github.com/dimforge/rapier/pull/531 be the correct candidate ?

**Comment by Ughuuu** [comment]
Sure, thats what I used locally.

**Comment by Vrixyz** [comment]
:tada: yay! I'd like to add a changelog line before merging though

**Pull request merged**
